import { parseISO } from 'date-fns';
import { Marco } from '../../domain/entities/marco';

enum StatusTarefa {
    PENDENTE = 'Pendente',
    EM_ANDAMENTO = 'Em andamento',
    CONCLUIDO = 'Concluido',
    CONCLUIDO_ATRASO = 'Concluido com atraso',
    NAO_INICIADO = 'Não iniciado',
    MARCO = 'Marco',
}
export const fakeTarefas = [
    {
        nome: 'Tarefa com nome muito grande 1',
        responsavel: { nome: 'Responsável 1' },
        data_inicio: parseISO('2025-10-01'),
        data_fim: parseISO('2025-10-05'),
        status: StatusTarefa.CONCLUIDO_ATRASO,
        id: 1,
        nivel: 1,
        num: 1,
        tarefas_filhas: [],
    },
    {
        nome: 'TTarefa com nome muito grande2',
        responsavel: { nome: 'Responsável 1' },
        data_inicio: parseISO('2025-10-03'),
        data_fim: parseISO('2025-10-05'),
        status: StatusTarefa.CONCLUIDO,
        id: 2,
        nivel: 2,
        num: 2,
        tarefas_filhas: [],
    },
    {
        nome: 'TTarefa com nome muito grande3',
        responsavel: { nome: 'Responsável 1' },
        data_inicio: parseISO('2025-10-06'),
        data_fim: parseISO('2025-10-10'),
        status: StatusTarefa.EM_ANDAMENTO,
        id: 3,
        nivel: 1,
        num: 2,
        tarefas_filhas: [],
    },
    {
        nome: 'TTarefa com nome muito grande3',
        responsavel: { nome: 'Responsável 1' },
        data_inicio: parseISO('2025-10-09'),
        data_fim: parseISO('2025-10-10'),
        status: StatusTarefa.EM_ANDAMENTO,
        id: 3,
        nivel: 1,
        num: 2,
        tarefas_filhas: [],
    },
    {
        nome: 'Tarefa com nome muito grande4',
        responsavel: { nome: 'Responsável 1' },
        data_inicio: parseISO('2025-10-11'),
        data_fim: parseISO('2025-10-15'),
        status: StatusTarefa.PENDENTE,
        id: 4,
        nivel: 1,
        num: 2,
        tarefas_filhas: [],
    },
    {
        nome: 'TTarefa com nome muito grande 5',
        responsavel: { nome: 'Responsável 1' },
        data_inicio: parseISO('2025-10-16'),
        data_fim: parseISO('2025-10-16'),
        status: StatusTarefa.NAO_INICIADO,
        id: 5,
        nivel: 1,
        num: 2,
        tarefas_filhas: [],
    },
    {
        nome: 'Tarefa com nome muito grande 6',
        responsavel: { nome: 'Responsável 1' },
        data_inicio: parseISO('2025-10-10'),
        data_fim: parseISO('2025-10-16'),
        status: StatusTarefa.CONCLUIDO,
        id: 5,
        nivel: 1,
        num: 2,
        tarefas_filhas: [],
    },
    {
        nome: 'Tarefa com nome muito grande6',
        responsavel: { nome: 'Responsável 1' },
        data_inicio: parseISO('2025-10-12'),
        data_fim: parseISO('2025-10-16'),
        status: StatusTarefa.CONCLUIDO_ATRASO,
        id: 5,
        nivel: 1,
        num: 2,
        tarefas_filhas: [],
    },
    {
        nome: 'Tarefa com nome muito grande6',
        responsavel: { nome: 'Responsável 1' },
        data_inicio: parseISO('2025-10-17'),
        data_fim: parseISO('2025-10-25'),
        status: StatusTarefa.NAO_INICIADO,
        id: 5,
        nivel: 1,
        num: 2,
        tarefas_filhas: [],
    },
    {
        nome: 'Tarefa com nome muito grande7',
        responsavel: { nome: 'Responsável 1' },
        data_inicio: parseISO('2025-10-26'),
        data_fim: parseISO('2025-10-29'),
        status: StatusTarefa.PENDENTE,
        id: 5,
        nivel: 1,
        num: 2,
        tarefas_filhas: [],
    },
    {
        nome: 'Tarefa 8',
        responsavel: { nome: 'Responsável 1' },
        data_inicio: parseISO('2025-10-30'),
        data_fim: parseISO('2025-11-05'),
        status: StatusTarefa.EM_ANDAMENTO,
        id: 5,
        nivel: 1,
        num: 2,
        tarefas_filhas: [],
    },
    {
        nome: 'Tarefa 9',
        responsavel: { nome: 'Responsável 1' },
        data_inicio: parseISO('2025-11-06'),
        data_fim: parseISO('2025-11-09'),
        status: StatusTarefa.CONCLUIDO_ATRASO,
        id: 5,
        nivel: 1,
        num: 2,
        tarefas_filhas: [],
    },
];
export const fakeMarcos: Marco[] = [
    { nome: 'Marco 1', id: 1 },
    { nome: 'Marco 2', id: 2 },
];

export const fakeProjetos = [
    {
        id: '1',
        nome: 'Desenvolvimento de Software',
        descricao: 'Descrição do projeto 1',
        status: 'andamento',
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '2',
        nome: 'Projeto 2',
        descricao: 'Descrição do projeto 2',
        status: 'andamento',
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '3',
        nome: 'Projeto 3',
        descricao: 'Descrição do projeto 3',
        status: 'andamento',
        createdAt: new Date(),
        updatedAt: new Date(),
    },
];
